swagger: "2:0"
info:
  description: "This is a HGP API server:"
  version: "1:0:0"
  title: "HGP"
  termsOfService: "http://hgp:io/terms/"
  contact:
    email: "apiteam@hgp:io"
  license:
    name: "Apache 2:0"
    url: "http://www:apache:org/licenses/LICENSE-2:0:html"
host: "localhost:8081"
basePath: "/"
tags:
- name: "guess"
  description: "All good guesses count"
  externalDocs:
    description: "Find out more"
    url: "http://swagger:io"
schemes:
- "http"
paths:
  /health:
    get:
      tags:
      - "health"
      summary: "Health point"
      description: "All generated responses returned:"
      operationId: "health"
      consumes:
      - "*/*"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Health"
        400:
          description: "Invalid status value"
  /team-member/{teamMemberId}/relationships:
    get:
      tags:
      - "teammember"
      summary: "Finds All relationships"
      description: "Finds All relationships:"
      operationId: "teamMemberRelationships"
      consumes:
      - "*/*"
      produces:
      - "application/json"
      parameters:
      - name: "teamMemberId"
        in: "path"
        description: "Team Member Id"
        required: true
        type: "string"
      - name: "sid"
        in: "query"
        description: "User Id"
        required: true
        type: "string"
      - name: "userType"
        in: "query"
        description: "User Type"
        required: true
        type: "string"
      - name: "roleType"
        in: "query"
        description: "Role Type"
        required: false
        type: "array"
        items: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ClientSummResults"
        400:
          description: "Invalid status value"


  /documents:
   get:
      tags:
      - "document"
      summary: "Finds All Documents"
      description: "Finds All Documents:"
      operationId: "documentsFor"
      consumes:
      - "*/*"
      produces:
      - "application/json"
      parameters:
      -
        name: "userId"
        in: "query"
        description: "User Id"
        required: true
        type: "string"
      -
        name: "userLob"
        in: "query"
        description: "User Object"
        required: true
        type: "string"
      -
        name: "teamListId"
        in: "query"
        description: "Team List Id"
        required: true
        type: "integer"
        format: "int32"
      -
        name: "teamList"
        in: "query"
        description: "Team List"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Document"
        400:
          description: "Invalid status value"

  /accounts:
    get:
      tags:
      - "account"
      summary: "Finds All Party Accounts"
      description: "Finds All Party Accounts:"
      operationId: "accountsForParty"
      consumes:
      - "*/*"
      produces:
      - "application/json"
      parameters:
      -
        name: "partyId"
        in: "query"
        description: "Party Id"
        required: true
        type: "integer"
        format: "int32"
      -
        name: "docId"
        in: "query"
        description: "Dccument Id"
        required: true
        type: "integer"
        format: "int32"
      -
        name: "docVersion"
        in: "query"
        description: "Dccument Version"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/DocAcc"
        400:
          description: "Invalid status value"
definitions:
  ClientSummResults:
    type: object
    id: com:jpmorgan:core:model:party:ClientSummResults
    properties:
      id:
        type: integer
    xml:
      name: "ClientSummResults"

  Document:
    type: object
    id: com:jpmorgan:ss:workstation:document:Document
    properties:
      docId:
        type: integer
    xml:
      name: "Document"
  DocAcc:
    type: object
    id: urn:jsonschema:com:jpmorgan:pcg:iws:model:DocAcc
    properties:
      docId:
        type: integer
    xml:
      name: "DocAcc"
  Health:
    type: "object"
    properties:
      health:
        type: "string"
    xml:
      name: "Health"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger:io"
